keys:
  - &yousiki_hakase age193dzgrrd3kzhe8ch6nxjskke74jph909d8w3ew4akzekeanjsv3sefkg7r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      age:
      - *yousiki_hakase